version: '3'
services:
    core_api:
        build: .
        container_name: 'core-api-contianer'
        ports:
            - "8000:15400"
        volumes:
            - ./Dockersss/:/Dockersss